<div class="container-fluid main-container">

<div id="header">

# p8105_hw2_td2809

#### Chris Deng

#### 2023-10-02

</div>

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

<div id="problem-1" class="section level1">

# Problem 1

First, clean the data in pols-month.csv. Use separate() to break up the
variable mon into integer variables year, month, and day; create a
president variable taking values gop and dem, and remove prez_dem and
prez_gop; and remove the day variable.

``` r
#clean the data in pols-month.csv
pols_month = 
  read_csv("C:/Users/邓添元/Documents/buildingblocks/p8105_hw2_td2809/fivethirtyeight_datasets/pols-month.csv") |>
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = T) |>
  mutate(
    president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop"),
    month = month.name[month]) |> 
  select(year, month, everything(), -day, -starts_with("prez"))
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Second, clean the data in snp.csv using a similar process to the above.

``` r
snp = 
  read_csv("C:/Users/邓添元/Documents/buildingblocks/p8105_hw2_td2809/fivethirtyeight_datasets/snp.csv",
           col_types = cols(date = col_date(format = "%m/%d/%y"))) |>
  separate(date, into = c("year", "month", "day"), convert = TRUE) |>
  mutate(
    year = if_else(year>2023,year-100,year),
    month = month.name[month]) |>
  select(year, month, close) 
```

Third, tidy the unemployment data.

``` r
month_df = 
  tibble(
    month_num = 1:12,
    month_abb = month.abb,
    month = month.name
  )


unemployment = 
  read_csv("C:/Users/邓添元/Documents/buildingblocks/p8105_hw2_td2809/fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month_abb",
    values_to = "unemployment"
  ) |> 
  left_join(x = _, y = month_df) |> 
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## Joining with `by = join_by(month_abb)`

Now merge three datasets

``` r
data_538 = 
  left_join(pols_month, snp) |>
  left_join(x = _, y = unemployment)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

Notice that there are some `NA` values in the `close` and `unemployment`
variables, which indicate that the value of these variables is missing
at those locations.

Let’s talk about the 538 datasets. The `pols_month` data has 822
observations and 9 variables and tells us about the party affiliation
distribution (democrat or republican) for governors and senators for a
given year from years 1947 to 2015. It also tells us whether the sitting
president was a democrat or republican. The `snp` data has 787
observations and 3 variables, ranging from years 1950 to 2015. The
`unemployment` data has 816 observations and 3 variables ranging from
years 1948 to 2015. In Januarys in or after 1975 in which a democrat was
president, the **average unemployment rate was 6.57**. The average
unemployment rate over the same time period in which a republican was
president was 6.47.

</div>

<div id="problem-2" class="section level1">

# Problem 2

Read and clean the Mr. Trash Wheel sheet:

``` r
library(readxl)
Mr_trash_wheel = 
  readxl::read_excel("C:/Users/邓添元/Documents/buildingblocks/p8105_hw2_td2809/202309 Trash Wheel Collection Data.xlsx", sheet = 1) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(homes_powered = round ((weight_tons * 500) / 30, 0),
         trashID = "Mr",
         year = as.numeric(year))|>
  select(-x15,-x16)
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

Use a similar process to import, clean, and organize the data for
Professor Trash Wheel and Gwynnda.

``` r
professor_trash_wheel = 
  readxl::read_excel("C:/Users/邓添元/Documents/buildingblocks/p8105_hw2_td2809/202309 Trash Wheel Collection Data.xlsx", sheet = 2, range = "A2:M108") |>
  janitor::clean_names() |>
  drop_na(dumpster)|>
  mutate(homes_powered = round ((weight_tons * 500) / 30, 0),
         trashID = "professor",
         year = as.numeric(year))

gwynnda_trash_wheel = 
  readxl::read_excel("C:/Users/邓添元/Documents/buildingblocks/p8105_hw2_td2809/202309 Trash Wheel Collection Data.xlsx", sheet = 4, range = "A2:L157") |>
  janitor::clean_names() |>
  drop_na(dumpster)|>
  mutate(homes_powered = round ((weight_tons * 500) / 30, 0),
         trashID = "gwynnda",
         year = as.numeric(year))

merge_trash = bind_rows(Mr_trash_wheel, professor_trash_wheel,gwynnda_trash_wheel)
```

Three datasets are involved in Problem 2, including *“Mr.”*,
*“Professor”* and *“Gwynnda”* Trash Wheel. Which containing 584, 106,
and 155 observations respectively. Moreover, there are common variables
involved in these three datasets, such as,

-   `month`, `year` and `date` for recording the time.
-   `weight_tons` and `volume_cubic_yards` represent the weights and
    volumes of the trash.
-   `plastic_bottles`, `polystyrene` and `cigarette_butts` indicate
    trash amount in different types.
-   `homes_powered` represents the average time that electricity
    converted from garbage can be used by a household.

Then merging these three datasets into one dataframe called
*“merge_trash”*, which contains 845 observations and 15 variables.

For available data, the total weight of trash collected by Professor
Trash Wheel was 216.26 tons, and the total number of cigarette butts
collected by Gwynnda in July of 2021 was 16,300.

</div>

<div id="problem-3" class="section level1">

# Problem 3

Import, clean, and tidy the dataset of baseline demographics.

``` r
baseline_original = read_csv("C:/Users/邓添元/Documents/buildingblocks/p8105_hw2_td2809/data_mci/MCI_baseline.csv", skip = 1, na = ".") |> 
  janitor::clean_names() |> 
  mutate(sex = recode(sex, `0` = "female", `1` = "male")) |> 
  mutate(apoe4 = recode(apoe4, `0` = "non-carrier", `1` = "carrier")) 
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
baseline = read_csv("C:/Users/邓添元/Documents/buildingblocks/p8105_hw2_td2809/data_mci/MCI_baseline.csv", skip = 1) |> 
  janitor::clean_names() |>
  mutate(sex = recode(sex, `0` = "female", `1` = "male")) |> 
  mutate(apoe4 = recode(apoe4, `0` = "non-carrier", `1` = "carrier")) |> 
  filter(age_at_onset!= ".")
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Discuss important steps in the import process and relevant features of
the dataset. The dataset contains 6 variables, they are id, current_age,
sex, education, apoe4, age_at_onset .483participants in total were
recruited. And 483 participants, 97 developed MCI. The average baseline
age is 65.6113402. 29.8578199% of the women in the study are APOE4
carriers.

Similarly, import, clean, and tidy the dataset of longitudinally
observed biomarker values.

``` r
library(tidyverse)
amyloid = read_csv("C:/Users/邓添元/Documents/buildingblocks/p8105_hw2_td2809/data_mci/mci_amyloid.csv", skip = 1, na = c("Na", "NA"))|>  # skip the first row
  janitor::clean_names() |>     # clean the variable names 
  pivot_longer(
    baseline:time_8,
    names_to = "time", 
    names_prefix = "time_", # skip the prefix 
    values_to = "amyloid" 
    ) |>
  mutate(time = recode(time, "baseline" = "0")) |> # change the baseline to 0 in time
  mutate(time = as.integer(time))  # change time to integers 
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

`read_csv` was applied to import *amyloid* data and
`janitor::clean_names()` was used to clean the column names.The dataset
has 2435 rows and 3 columns and including variables are study_id, time,
amyloid, which represents the time(in years) elapsed since the study
baseline to the visit where biomarker amyloid 42/40 ratio was measured.

Check whether some participants appear in only the baseline or amyloid
datasets, and comment on your findings.

``` r
# Check for participants appear only in the baseline dataset 
subset(baseline_original, !(id %in% amyloid$study_id))
```

    ## # A tibble: 8 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ## 1    14        58.4 female        20 non-carrier         66.2
    ## 2    49        64.7 male          16 non-carrier         68.4
    ## 3    92        68.6 female        20 non-carrier         NA  
    ## 4   179        68.1 male          16 non-carrier         NA  
    ## 5   268        61.4 female        18 carrier             67.5
    ## 6   304        63.8 female        16 non-carrier         NA  
    ## 7   389        59.3 female        16 non-carrier         NA  
    ## 8   412        67   male          16 carrier             NA

``` r
# Check for participants appear only in the amyloid dataset 
subset(amyloid, !(study_id %in% baseline_original$id))
```

    ## # A tibble: 60 × 3
    ##    study_id  time amyloid
    ##       <dbl> <int>   <dbl>
    ##  1      484     0   0.111
    ##  2      484     2   0.111
    ##  3      484     4   0.109
    ##  4      484     6   0.111
    ##  5      484     8   0.107
    ##  6      485     0   0.106
    ##  7      485     2   0.105
    ##  8      485     4   0.108
    ##  9      485     6   0.107
    ## 10      485     8   0.106
    ## # ℹ 50 more rows

There are 6 of participants appear only in the baseline dataset and 12
of participants appear only in the amyloid dataset.

Combine the demographic and biomarker datasets so that only participants
who appear in both datasets are retained, and briefly describe the
resulting dataset; export the result as a CSV to your data directory.

``` r
amyloid_baseline = inner_join(amyloid, baseline_original, by = join_by("study_id" == "id"))
```

``` r
write_csv(amyloid_baseline, "C:/Users/邓添元/Documents/buildingblocks/p8105_hw2_td2809/data_mci/amyloid_baseline.csv")  # export the result as a CSV 
```

After combining baseline and amyloid data with participants that
appearing in both datasets, the merging dataset contains 2375
observations and 8 variables. There are study_id, time, amyloid,
current_age, sex, education, apoe4, age_at_onset variables in the
merging dataset. And 475 participants appears in both datasets.

</div>

</div>
